# Generated by Django 5.1.5 on 2025-01-29 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('category', models.CharField(choices=[('bouquet', 'Букеты'), ('single', 'Одиночные цветы'), ('composition', 'Композиции')], max_length=50, verbose_name='Категория')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('quantity_sold', models.PositiveIntegerField(default=0, verbose_name='Количество реализованных заказов')),
                ('available_quantity', models.PositiveIntegerField(default=0, verbose_name='Количество доступное для заказа')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='products/', verbose_name='Изображение')),
            ],
        ),
    ]
